### ISSUE TITLE
Write color in rgb?

### ISSUE THREAD

**Issue by marvin2k** [theZiz/aha#10]
Hi,

not sure if this is possible at all, but could `aha` query the current rgb-mapping of, for example, the color _green_ and insert this value instead of the name into the html?

Greetings

**Comment by theZiz** [comment]
Hi,

From where? From the terminal settings or from the CSS settings? I doubt the first is possible and the second doesn't make much sense for me as you can change the CSS file however you want green to look like. What do you want to do?

Greetings,
Alex

**Comment by marvin2k** [comment]
I'm looking for a way to insert terminal output into a latex/beamer document. In the moment I use `aha` to create html, and then a (hacky) sed script to massage it into tex.

Querying the color is possible using [xrdb --qeruy](https://bbs.archlinux.org/viewtopic.php?pid=1179565#p1179565) for example.

**Comment by theZiz** [comment]
Interesting! However I think your sed attempt is way better than hacking a solution to aha just for this case. :) Couldn't you e.g. even replace green e.g. with \green and define is somewhere as the green colour you would like to have?

**Comment by marvin2k** [comment]
Yeah, I fear I'll end up with something like this... But still, it would be a nice feature of `aha` to be able to replicate the whole terminal _as_it_was_, including the _exact_ text- and background colors.

**Comment by theZiz** [comment]
Yes, you are right. I will absolutely think about it. :)

**Comment by jamadagni** [comment]
Not to decry @theZiz 's work but @marvin2k may want to try [ansifilter](http://www.andre-simon.de/doku/ansifilter/en/ansifilter.php) which does HTML, TeX and other formats.

**Comment by marvin2k** [comment]
Ah. As far as I remember I played around with ansifilter, but due to some unknown reason didn't use it in the end... But I cannot tell why any more... ;-) It saw some releases since back then, so...

**Comment by theZiz** [comment]
Well, I guess this issue is ready to be closed.
