### ISSUE TITLE
Please specify more clearly the license

### ISSUE THREAD

**Issue by krytarowski** [theZiz/aha#14]
MPL-1.1 or what version of LGPL? Any?

Thank you

**Comment by theZiz** [comment]
Tbh I don't care. LGPL2+ and MPL1.1 sounds good. I don't need compatibility with GPL (obviously), so MPL 1.1 sounds good, too. However if you need MPL2.0 for some reason, I am fine with this, too. I will update the informations in the README the next days. I didn't tinker with licenses for a long time. These days I choose just GPL2+ for most new projects.

**Comment by krytarowski** [comment]
I'm ok with `LGPL+`, so any LGPL (2.0, 2.1, 3.0 or later). This wasn't explicitly set. Please add a note about it.

This is what I used in the pkgsrc package http://pkgsrc.se/textproc/aha

**Comment by xtaran** [comment]
For Debian I assumed "MPL 1.1 or LGPL-3+". But I'm fine with any of the mentioned licenses if it makes the licensing clearer. :-)

**Comment by theZiz** [comment]
LGPL2+ does include LGPL3+, so you don't need to change anything @xtaran, do you?

**Comment by xtaran** [comment]
I do have to change that if you go with LGPL2+, but that's no reason to _not_ choose LGPL2+.
