### ISSUE TITLE
Please note pkgsrc (NetBSD) support in README

### ISSUE THREAD

**Issue by krytarowski** [theZiz/aha#16]
Installation from prebuilt packages:

```
pkgin install aha
```

Installation from sources

```
cd /usr/pkgsrc/textproc/aha && make install
```

**Comment by theZiz** [comment]
Hm, is the readme the right place to explain, how to install aha for every system? Or is a comment like "aha supports pkgsrc from NetBSD" enough?

**Comment by krytarowski** [comment]
It looks appropriate to put it into README.

An example: https://github.com/fcambus/logswan

**Comment by theZiz** [comment]
I still don't want to have installation hints for every system in my README. I guess an interested NetBSD user will figure it out [his|her]self if your proposed way it the default way for installing software on your system.
