### ISSUE TITLE
Remove reference to http://ziz.delphigl.com/tool_aha.php

### ISSUE THREAD

**Issue by jpluimers** [theZiz/aha#18]
The HTML mentions http://ziz.delphigl.com/tool_aha.php but that page is down so you probably want to remove the reference or point it to https://github.com/theZiz/aha

**Comment by theZiz** [comment]
You are right, I will fix this! Thanks!

**Comment by theZiz** [comment]
Fixed, https://github.com/theZiz/aha/commit/15ff70b8c5491f32b7c5d4f73922e9e0d8cbe932

**Comment by jpluimers** [comment]
Great. You still do Delphi?

**Comment by theZiz** [comment]
No, since ages not. From time to time I hack something in Lazarus, but more because it is the easiest way for me to do a quick GUI program. Nothing I would show other people. ;)
