### ISSUE TITLE
Image: Positive (27) doesn't cancel out Image: Negative (7) correctly

### ISSUE THREAD

**Issue by normanr** [theZiz/aha#19]
I've trying to use aha with output generated by:

file1:
this is a test

file2:
this is also a test

diff -u file1 file2 | diff-highlight | aha > diff.html

This results in the end of line 1 (and line 2) being a weird background color.  I expect a white background (no background color overridden), but it's gray instead.

It looks like the ^[27m isn't cancelling the ^[7m correctly.

diff-highlight can be found at git/contrib/diff-highlight

**Comment by theZiz** [comment]
Well, I just found a big "//TODO" in my code around the invertation code.

I will fix this. ;)

**Comment by theZiz** [comment]
Sorry, that I needed a whole month, but I really didn't find any time. But now it should be fixed in commit d53b5e0d9a5ca34fc477373844ea646c53f0e030.
