### ISSUE TITLE
Bold doesn't appear to reset

### ISSUE THREAD

**Issue by eanderson4** [theZiz/aha#24]
Issue:  In my terminal, the output of my npm run has only 1 word in bold.  The output in my html file after running aha has all the following words in bold as well.  

see dump of files here: [https://gist.github.com/eanderson4/807cc5dc676e8be291863c0bc043aa33](https://gist.github.com/eanderson4/807cc5dc676e8be291863c0bc043aa33)

I run the following command to keep the ansi escape characters in a log.

$ unbuffer npm start > npm.log
$ cat npm.log | ./aha > npm.html

In the terminal, only 'Access URLs:' appears to be bold.  However, in the html file, every word that follows is in bold.  I don't really know much about these ansi characters to debug anything so I was wondering if there is any obvious mistake I was making in this.

$ ./aha --version
Ansi Html Adapter Version 0.4.10.3

And thank you for this program, it is very useful!  Much appreciated.

Eric

**Comment by theZiz** [comment]
Thanks for the bug report.
Could you also provide me the "npm.log", I have neither `unbuffer` nor  `npm` installed. :)

**Comment by eanderson4** [comment]
[?25l[[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.9.2[K
[[90m..................[0m] - : [32minfo[0m [35musing[0m node@v6.9.2[K

[[90m07:08:03[39m] Requiring external module [35mbabel-register[39m
[[90m07:08:05[39m] Starting '[36mtemplates[39m'...
[[90m07:08:05[39m] Finished '[36mclean[39m' after [35m368 ms[39m
[[90m07:08:05[39m] Starting '[36mcopy[39m'...
[[34mBS[39m] [1mAccess URLs:[22m
[90m --------------------------------------[39m
       Local: [35mhttp://localhost:4000[39m
    External: [35mhttp://192.168.0.106:4000[39m
[90m --------------------------------------[39m
          UI: [35mhttp://localhost:3001[39m
 UI External: [35mhttp://192.168.0.106:3001[39m
[90m --------------------------------------[39m
[[34mBS[39m] Serving files from: [35m./dist/[39m
[[34mBS[39m] Watching files...
[[90m07:08:06[39m] Finished '[36mcopy[39m' after [35m946 ms[39m
[[90m07:08:07[39m] Finished '[36mtemplates[39m' after [35m1.45 s[39m
[[90m07:08:12[39m] Finished '[36mdefault[39m' after [35m3.34 μs[39m

**Comment by eanderson4** [comment]
I tried to paste into the gist too, never posted a report so new to this.  Thanks for the quick response!

**Comment by theZiz** [comment]
Sorry for the late respone time, I will have a look at this bug today or the weekend. ;)

**Comment by theZiz** [comment]
Sorry for the late answer, I had less time on the weekend than expected. I fixed it: https://github.com/theZiz/aha/commit/38db4c1fbb3a32669e823ef1c35d7b1f7fc62547
I just forgot to check for the command 22: reseting bold text, I did only check for command 0 (reseting everything) and 21 (resetting bold and double underline)

**Comment by eanderson4** [comment]
It looks like it is working, thanks for the fix!
