### ISSUE TITLE
using aha with "tee" command.

### ISSUE THREAD

**Issue by anbreen** [theZiz/aha#25]
is it possible to use aha with "tee"
I want to display the output of my command on the console as well as pipe it using "aha" to an html file

**Comment by theZiz** [comment]
Sure, why not? Aha is just another terminal tool. :D I quickly googled this:
https://unix.stackexchange.com/questions/40277/is-there-a-way-to-pipe-the-output-of-one-program-into-two-other-programs
So this here shows the aha help on the terminal **and** prints it to `aha.html`:
```Bash
aha --help | tee >(aha --black > aha.html)
```
I hope, this helps. :)

**Comment by anbreen** [comment]
great. thanks :)
