### ISSUE TITLE
not capturing text background color

### ISSUE THREAD

**Issue by afeld** [theZiz/aha#29]
_I don't know much about how ANSI colors work, so forgive my ignorance here._

I'm trying to save colorized `git diff` output to HTML, but am having an issue where the background colors aren't appearing in the HTML. Running the following command:

```sh
git diff -w --color old.txt new.txt | aha --black > diff.html
```

Terminal output:

![screen shot 2017-04-07 at 1 48 44 pm](https://cloud.githubusercontent.com/assets/86842/24812966/361f767c-1b9a-11e7-8998-341a1cbfb27c.png)

Rendered Aha HTML:

![screen shot 2017-04-07 at 1 49 06 pm](https://cloud.githubusercontent.com/assets/86842/24812975/432ec534-1b9a-11e7-9492-f79a20f8102c.png)

I tried [ansifilter](http://www.andre-simon.de/doku/ansifilter/en/ansifilter.php) as well and had the same problem, so I wonder if it might be something weird with how [`diff-highlight`](https://github.com/git/git/tree/master/contrib/diff-highlight) does background colors or something?
 Potentially-relevant lines from my `.gitconfig`:

```ini
[color]
        ui = true
[pager]
        diff = diff-highlight | less
```

and software versions:

```
$ aha --version
Ansi Html Adapter Version 0.4.10.6
$ git --version
git version 2.12.2
hub version 2.2.9
```

Tested using ZSH on iTerm and Terminal. Awesome project, thanks!

**Comment by theZiz** [comment]
Thanks for the issue! I will have a deeper look into this :)

**Comment by theZiz** [comment]
Hm, I cannot reproduce the output on my system.
Could you please run the following command and give me the resulting `output.txt`?
```Bash
git diff -w --color old.txt new.txt > output.txt
```
Can can also check with `cat output.txt`, whether the color code are inside the file, but for me it worked.

**Comment by theZiz** [comment]
bump @afeld ?

**Comment by larseggert** [comment]
I have the same issue. Here is how it looks in the shell:
<img width="653" alt="screen shot 2017-08-24 at 12 08 48" src="https://user-images.githubusercontent.com/200328/29683959-0e940c38-88c5-11e7-847e-076b3096adc5.png">

When I view it in a browser after processing with aha, it looks like this:
<img width="734" alt="screen shot 2017-08-24 at 12 10 04" src="https://user-images.githubusercontent.com/200328/29684001-36a68476-88c5-11e7-8a08-1c908c4b565d.png">

Source and HTML files below:
[out.txt](https://github.com/theZiz/aha/files/1249966/out.txt)
[out.html.zip](https://github.com/theZiz/aha/files/1249970/out.html.zip)

**Comment by theZiz** [comment]
Hey and sorry for the late response, but I finally had time to have a look at your issue. It seems, that I interpretate `ESC[7m` wrong, which tells the terminal emulator to negate the colours. I thought the set colours need to be inverted, but furthermore every following colour codes need to be interpretated inverted, too.

**Comment by theZiz** [comment]
@larseggert I think I have fixed the issue, please try the most recent version.
![fix](https://user-images.githubusercontent.com/385145/30582699-f89ca02e-9d24-11e7-90a7-832e538cf82d.png)

**Comment by larseggert** [comment]
Will do, but might take a while. (I changed my code to not emit the "reverse" code, so I need to roll back to an earlier version.)

**Comment by theZiz** [comment]
No problem, sorry for the long delay.
