### ISSUE TITLE
Can't get terminal table characters to show correctly in the output

### ISSUE THREAD

**Issue by eblis** [theZiz/aha#31]
I have a script that generates pretty terminal tables that I'd like to convert to HTML using AHA.
The output in the console looks like this:
![image](https://user-images.githubusercontent.com/540188/30208849-f4110c00-949d-11e7-9a0a-9f89fd955a7b.png)

But once it has been parsed by aha it looks like this:
![image](https://user-images.githubusercontent.com/540188/30208919-40b43f8c-949e-11e7-9f27-fa3a21220303.png)

The bars/lines are all messed up. I have encountered a very similar issue with tmux in the past, where the problem was that tmux was showing these characters instead of pretty tables but can be solved by forcing tmux in unicode mode with -u flag.
Is there something similar I could use for this ?

If it makes any difference I'm using aha through pipes, like this:
```
data=$(./status.py $@)
echo -e "$data" | aha
```

**Comment by theZiz** [comment]
Sorry, I had a lot of work to do in the last days. I will have a look at this issue right now. :smiley:

**Comment by theZiz** [comment]
Could you give me the script or at least the output from the script? Maybe try this:
`your_script.sh > output.txt`
`cat output.txt | aha`
If this triggers the same wrong behaviour, the `output.txt` would be sufficient for debuggung the behaviour. ;)

**Comment by eblis** [comment]
I've gotten around the issue by using unicode characters for the table borders, but the issue still occurs if you use escape sequences.

Here's an output that triggers the issue: [bug.txt](https://github.com/theZiz/aha/files/1313503/bug.txt)

![image](https://user-images.githubusercontent.com/540188/30582714-678e5e98-9d2d-11e7-9e7b-76762fafc844.png)

**Comment by theZiz** [comment]
Thanks, I could reproduce the problem and dig deep into the blacj magic of vt220 terminal emulation. What I figued out until now: Your output uses ESC(0, which enables a special graphic set for such tables as described here http://www8.cs.umu.se/~isak/snippets/vt100.txt
It was hard to find the corresponding character set, but finally I found it here https://whitefiles.org/b1_s/1_free_guides/fg2cd/pgs/c03b.htm

Although you found a work around I will try to implement at least these special characters in aha. :)

**Comment by eblis** [comment]
If you're familiar with Python the tool that generates those borders is [terminaltables](https://github.com/Robpol86/terminaltables) using [SingleTable](https://github.com/Robpol86/terminaltables/blob/master/terminaltables/other_tables.py#L122) class (which translated to [UnixTable](https://github.com/Robpol86/terminaltables/blob/master/terminaltables/other_tables.py#L7) on Linux systems).

**Comment by theZiz** [comment]
Thanks for the hint, but I tried to implement the table myself using the html special char namings. It seems to work now:
![fix3](https://user-images.githubusercontent.com/385145/30587215-a8f58226-9d32-11e7-8a14-2635c85d7a15.png)
I still need to add the rest of the table, but for you this should already work. Please have a look!

**Comment by eblis** [comment]
Looks good, thanks.

**Comment by theZiz** [comment]
I hope it helps you :smiley:
