### ISSUE TITLE
[Help] How do I view output on terminal too?

### ISSUE THREAD

**Issue by regalstreak** [theZiz/aha#33]
Great work. Is there any way I could view output in terminal and get the htm simultaneously? I am doing android builds and these are very long and it'll be great if we can have output on terminal as well as an htm

**Comment by theZiz** [comment]
`tee` is what you want, e.g.
```
aha --help | tee >(aha --black > output.htm)
```
You could also further process the output of your command with another `|`in the end. See also here: https://unix.stackexchange.com/questions/40277/is-there-a-way-to-pipe-the-output-of-one-program-into-two-other-programs
