### ISSUE TITLE
RPM Package

### ISSUE THREAD

**Issue by scx** [theZiz/aha#37]
I created RPM packages for EL (6, 7), Fedora (26, 27, 28, 29), Mageia (6, 7), openSUSE (Leap 15.0, Tumbleweed). I hope it will be useful for someone.
RPM SPEC: http://pastebin.centos.org/876726/15301392/raw/
Repos: https://copr.fedorainfracloud.org/coprs/scx/aha/

**Comment by theZiz** [comment]
Nice, thanks!

Will they somehow be updated automatically when I release a new version / tag like for the debian version?

**Comment by scx** [comment]
@theZiz 
No, this is strictly tied to the *0.4.10.6* version. With such a range of supported distributions, too many things can go wrong with automatic rebuilding. This is possible, but is mainly intended for testing purposes.
https://docs.pagure.org/copr.copr/user_documentation.html#scm
https://docs.pagure.org/copr.copr/webhook_hacking.html
https://hobo.house/2017/09/03/automate-rpm-builds-from-git-sources-using-copr/
https://clime.github.io/2017/10/24/COPR-SCM.html

**Comment by theZiz** [comment]
Nevertheless thanks for your work :)
