### ISSUE TITLE
"cat" of ANSI Color preserved file ends up w/o color

### ISSUE THREAD

**Issue by jlpoolen** [theZiz/aha#52]
I created a capture file of ANSI colors of a session of ffmpeg, see attached [ansible-output.txt](https://github.com/theZiz/aha/files/2429837/ansible-output.txt).

Then:

>  cat ansible-output.txt |aha >aha_out.htm

the file aha_out.htm is just black and white.
Is something getting lost in the "cat" command?  Is there a way to push saved ANSI encoded content through aha?

**Comment by jlpoolen** [comment]
Attached is a screen shot showing the array of colors ffmpeg produces that are preserved in asnible-output.txt

![putty_2018-09-28_14-49-04](https://user-images.githubusercontent.com/227313/46235150-e48a1780-c32d-11e8-881e-399f473322d6.png)

**Comment by jlpoolen** [comment]
I thought it might be helpful to turn focus onto an isolated instance.  Using as an example the line which is colored red and has "error while decoding...":
![putty_2018-09-28_16-53-18](https://user-images.githubusercontent.com/227313/46238307-777f7d80-c33f-11e8-9c35-e372b1f62255.png)

the HTML is:
`</span><span style="color:white;text-decoration:blink;">[h264 @ 0x558f9c9e65b0] </span><span style="color:black;text-decoration:blink;">error while decoding MB 74 88, bytestream -5`
and within an text editor, the line looks like:
![notepad _2018-09-28_16-51-10](https://user-images.githubusercontent.com/227313/46238311-80704f00-c33f-11e8-9ff0-f30fc456deef.png)

So the control code preceding "error" is: [38;5;196m

I'm guessing here, but the 196 may represent the color "red" as designated in an 8 bit (256 color) table.  See https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit

Since the span style preceding "error while..." is "color:black;text-decoration:blink;", I'm thinking somewhere in the cases following the switch statement at line 555+ is pertinent.

I'm using Xming on Windows7 through PuTTY, though the sample file I posted in a previous comment was derived from an xterm running in XFCE on a laptop.

**Comment by jlpoolen** [comment]
I also wondered if cat and/or piping might have caused a change.  I have concluded it does not:

     jlpoole@ares /tmp $ cat ansible-output.txt >after_cat.txt
     jlpoole@ares /tmp $ diff ansible-output.txt after_cat.txt 
     jlpoole@ares /tmp $

**Comment by jlpoolen** [comment]
I created a test file consisting of a portion of a single line where the word "error" should be in red.  The file is attached as "error.txt"
[error.txt](https://github.com/theZiz/aha/files/2431768/error.txt)

Note: I have added several "printf" lines to my version of the code for debugging purposes.  Thus, the line numbers I have may be off by a few numbers.  During my debug session, I found variable "fc" to be the value of 8:

`@line 500, a switch stmt, fc = 8

"fc" - only lines altering are:

     332 = -1  # initialized as int
     387 = -1
     419 = 7
     421 = 0
     424 = temp
     429 fc=momelem->digit[mompos+1];
     451 = 7
     453 = 0
     456 = temp

"temp" - only lines altering are:

       341 # declarated as int, but not not initialized
       406 = bc
       438 = bc

"bc" - only lines latering are:

   333 = -1
   410 = 0
   412 = 7
   415 = fc
   442 = 0
   444 = 7`

Since there is not code that sets the value of "fc" to 8, then it must be occurring at line 429, the problem may be occurring with the structure or the call to it at line 429.

**Comment by jlpoolen** [comment]
for posterity, my terminal in Xfce is:

     xfce4-terminal
     0.8.7.2
     docs.xfce.org/apps/terminal/start
     website is down at 10:35 a.m. PDT 9/30/2018

The color output was generated from ffmpeg's STDERR.  Here's an example of the command I used to generate the STDERR file:

     ffmpeg -i rtsp://[XXX/XXX]:@[XXX]  /tmp/video/test.mp4 2>/tmp/redirect_stderr.txt |tee /tmp/tee_test4.txt

**Comment by jlpoolen** [comment]
I activated a debug line ~375 which prints out the control code.  In my example using the even-further-reduced sample file, 
[error_shortened.txt](https://github.com/theZiz/aha/files/2432031/error_shortened.txt), the single code in the file is printed out as:

         [375] Control Code: [38;5;196

At line ~429, variable "fc" is set to "8", from the "38" above -- 8 being the 2nd digit.  The switch statements that follow ~500 for "fc", only hand 0-7 suggesting support only for the 3/4_bit color table.  The case of fc=8 falls through to case 9 at line ~554 which is effectively a reset: black on white.

Therefore, I am concluding that aha cannot handle 8 bit (216 colors) ANSI color coding.  My output is encoded in 8 bit, hence the HTML ends up being black on white.

This was a fun adventure.  Question now is: do I write a routine that handles 8 bit?  Time will tell.

**Comment by jlpoolen** [comment]
I really wanted this feature, so I cloned the project (for Eclipse) added a lot of debug lines and some comments and came up with a heuristic to deal with 256 colors.  I am not a proficient C coder, Perl is my forte and I only come into C when necessary such as for this project.  Hence I may have made some egregious errors so proceed with caution.  I spend a lot of time trying to understand the the data structures -- looking at the existing code did not cause me to quickly uptake the design.  Any rate, for what it is worth, see my modification and adapt as you deem fit.

https://github.com/jlpoolen/aha/blob/master/aha.c

I decided to upload my entire Eclipse settings plus all the debug so if someone else wants a ready-to-run development instance, it's here.  Note: makefile had to be amended to include debugging for gdb, my inexperience in that area cost me a good deal of time wondering my I could not step through the code in debug mode within Eclipse.

**Comment by theZiz** [comment]
Hey, sorry for the late response. As you noticed `aha` does not support 256 color ANSI. I am looking at your work around. I wondering why your solution is based on such an old version of aha. I will see whether I can use your `make_rgb` function for a working solution for a recent `aha`. :smiley:

**Comment by theZiz** [comment]
Okay, I merged your function in the most recent aha branch. For me your example works now. Thanks for your help. :smiley:

**Comment by jlpoolen** [comment]
In Issue #32 you asked for examples; the only ones I have are generated from ffmpeg and are 8 bit modes.  I'll test your version later and re-open this issue if I run into problem.  Thank you.
