### ISSUE TITLE
CSS option

### ISSUE THREAD

**Issue by madprops** [theZiz/aha#68]
Would be cool if there's a way to specify a css file to use. 

Something like --css=style.css

And then it just injects the tag into the header.

I could just do it with extra commands, but it would be easier this way.

Or at least some style options like font size.

**Comment by theZiz** [comment]
Do get this clear: You wish to add `<link rel="stylesheet" href="stylesheet.css" />` to the header if a `stylesheet.css` is given as argument?

**Comment by madprops** [comment]
The idea is that if a user wants to customize the style of the output a bit, they can just do so through a css file that would be referenced in the html document. So `--css=style.css` would just include `<link rel="stylesheet" href="style.css" />` in the header, letting the user create that file and write the custom styling rules.

**Comment by theZiz** [comment]
The short answer would have been just "yes" :sweat_smile: 

I'll give it a shot the next weeks ;)
