### ISSUE TITLE
`make install` does not work on macOS

### ISSUE THREAD

**Issue by IngoMeyer441** [theZiz/aha#79]
Hey,
thanks for your project. Currently, `make install` does not work on macOS since the `install` command does not support the `-D` option.

**Comment by freeeflyer** [comment]
I just proposed a PR: https://github.com/theZiz/aha/pull/80

**Comment by freeeflyer** [comment]
@theZiz ?

**Comment by theZiz** [comment]
Sorry for the long wait, rough time with a long mail todo...

Thanks for your work, looks good to me! :D
